
# K8 works with using API

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # naming the deployment

spec:
  selector:
    matchLabels:
      app: nginx # look for this label to match with k8 server
  
  # Creating 2 instance of the same container
  replicas: 2

# template to use it's label for k8 server to lunch container
  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx
          image: delwar987/first_repo:latest # image you want to build
          ports:
          - containerPort: 80
